kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# uncomment networking and insert your ip address if you install kind server on remote server not your localhost
# networking:
#   apiServerAddress: {your_ip_address}
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 30001
        hostPort: 30011
        protocol: TCP