apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-deployment-manager
  namespace: app-dev
rules:
- apiGroups: [""]
  resources: ["pods", "deployments"]
  verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-deployment-manager-binding
  namespace: app-dev
subjects:
- kind: ServiceAccount
  name: app
  namespace: app-dev
roleRef:
  kind: Role
  name: pod-deployment-manager
  apiGroup: rbac.authorization.k8s.io