reloader:
  reloader:

    enableHA: true
    replicas: 2t

    watchGlobally: true
    deployment:
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 50Mi
        
  
