apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  template:
    spec:
      containers:
      - name: test
        image: busybox:1.28
        command:
          - /bin/sh
          - -c
          - date; echo Hello from the Kubernetes cluster
      restartPolicy: Never
  backoffLimit: 4