apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 1000m
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 200Mi
  