apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  # property-like keys; each key maps to a simple value
  app_test_name: "apppppp"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true    